### PR TITLE
Remove 2dii refs

### LINKED ISSUE #490: Remove all references to 2DII
- [x] DESCRIPTION file
- [x] GH actions
- [x] (Maybe) License file(s)
- [ ] Function docs
- [x] README
- [ ] pkgdown links
- [ ] vignettes
- [ ] update NEWS.md (if relevant)

Relates to https://github.com/RMI-PACTA/r2dii.data/issues/295

### PR DESCRIPTION
**Pull request by jdhoffa**
Closes #490

### CODE REVIEW

**Review by MonikaFu — APPROVED** [review]
LGTM

**Comment by jdhoffa** [comment]
I see there's a bunch of CI checks failing. Will have a look

**Comment by jdhoffa** [comment]
Ok, should we merge this as-is and handle the unrelated check failures separately?

**Comment by MonikaFu** [comment]
@jdhoffa yes, sounds good to me. Will you make an issue for it?

**Pull request merged**
